name: Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    name: Build & Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rubik
            asset_name: rubik-linux-amd64
          - os: macos-latest
            artifact_name: rubik
            asset_name: rubik-macos-amd64
          - os: windows-latest
            artifact_name: rubik.exe
            asset_name: rubik-windows-amd64.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev pkg-config

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build Release
      run: cargo build --release

    - name: Rename Artifact
      run: |
        mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}
      shell: bash

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
